server:
  port: 8080

app:
  otp:
    ttl-seconds: 300

spring:
  mail:
    host: smtp.mailosaur.net
    port: 587
    username: ${MAILOSAUR_SMTP_USERNAME}
    password: ${MAILOSAUR_SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
